In [1]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print(a)

[10 20 30 40 50]


In [2]:
import numpy as np

def temperature_analysis(temp):

    average = np.mean(temp)
    maximum = np.max(temp)
    minimum = np.min(temp)

    highest_day = np.argmax(temp) + 1

    above_average = temp[temp > average]

    print("Average:", average)
    print("Maximum:", maximum)
    print("Minimum:", minimum)
    print("Highest Temperature Day:", highest_day)
    print("Above Average:", above_average)


temp = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])

temperature_analysis(temp)

Average: 31.842857142857145
Maximum: 34.5
Minimum: 29.8
Highest Temperature Day: 5
Above Average: [32.5 33.1 34.5]


In [3]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("First row:")
print(a[0])

print("Last row:")
print(a[-1])

print("First column:")
print(a[:, 0])

print("Last column:")
print(a[:, -1])

print("Middle 2x2:")
print(a[0:2, 1:3])

print("Alternate elements:")
print(a.flatten()[::2])

print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Number of elements:", a.size)

First row:
[1 2 3 4]
Last row:
[ 9 10 11 12]
First column:
[1 5 9]
Last column:
[ 4  8 12]
Middle 2x2:
[[2 3]
 [6 7]]
Alternate elements:
[ 1  3  5  7  9 11]
Shape: (3, 4)
Dimensions: 2
Number of elements: 12


In [4]:
import numpy as np

a = np.random.permutation(np.arange(1, 51))

print("Random numbers:")
print(a)

even = a[a % 2 == 0]
odd = a[a % 2 != 0]

print("Even numbers:")
print(even)

print("Odd numbers:")
print(odd)

Random numbers:
[48 33 18 41 34 39 26 50  9 35 31 27 36  7 45 10  1 15 49 17 11 38 44 42
 47 19 37 14  3 21 24 46 13 40 29 43 20 28 23 30 12 16 25 32  5 22  6  8
  4  2]
Even numbers:
[48 18 34 26 50 36 10 38 44 42 14 24 46 40 20 28 30 12 16 32 22  6  8  4
  2]
Odd numbers:
[33 41 39  9 35 31 27  7 45  1 15 49 17 11 47 19 37  3 21 13 29 43 23 25
  5]


In [5]:
import numpy as np

a = np.random.randint(1, 101, 30)

print("Array:")
print(a)

above_50 = a[a > 50]

between = a[(a >= 25) & (a <= 75)]

print("Numbers greater than 50:")
print(above_50)

print("Numbers between 25 and 75:")
print(between)

print("Count greater than 50:")
print(len(above_50))

print("Average greater than 50:")
print(np.mean(above_50))

Array:
[ 6  6 31 87 29 19 10 69 84  4  1 95 39 36 26  5 49 32 36 38 35 42 17 55
 23 58 24 13 29 88]
Numbers greater than 50:
[87 69 84 95 55 58 88]
Numbers between 25 and 75:
[31 29 69 39 36 26 49 32 36 38 35 42 55 58 29]
Count greater than 50:
7
Average greater than 50:
76.57142857142857


In [6]:
import numpy as np

marks = np.array([
    [78, 82, 91],
    [65, 74, 80],
    [92, 88, 95],
    [56, 69, 72],
    [84, 90, 87]
])

students = np.mean(marks, axis=1)
subjects = np.mean(marks, axis=0)

print("Student averages:")
print(students)

print("Subject averages:")
print(subjects)

print("Highest mark:", np.max(marks))
print("Lowest mark:", np.min(marks))

print("Best student:", np.argmax(students) + 1)

print("Best subject:", np.argmax(subjects))

Student averages:
[83.66666667 73.         91.66666667 65.66666667 87.        ]
Subject averages:
[75.  80.6 85. ]
Highest mark: 95
Lowest mark: 56
Best student: 3
Best subject: 2


In [7]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Addition:")
print(A + B)

print("Subtraction:")
print(A - B)

print("Element-wise multiplication:")
print(A * B)

print("Matrix multiplication:")
print(A @ B)

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [8]:
import numpy as np

def calculate(data):

    square = data ** 2
    root = np.sqrt(data)
    exponential = np.exp(data)

    print("Square:")
    print(square)

    print("Square root:")
    print(root)

    print("Exponential:")
    print(exponential)

    print("Mean of square:", np.mean(square))
    print("Mean of square root:", np.mean(root))
    print("Mean of exponential:", np.mean(exponential))


data = np.array([2, 4, 6, 8, 10, 12])

calculate(data)

Square:
[  4  16  36  64 100 144]
Square root:
[1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]
Exponential:
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]
Mean of square: 60.666666666666664
Mean of square root: 2.5530849508680995
Mean of exponential: 31371.271866746192


In [9]:
import numpy as np

a = np.arange(1, 25)

a1 = a.reshape(4, 6)
a2 = a.reshape(6, 4)
a3 = a.reshape(2, 3, 4)

print("4 x 6:")
print(a1)
print("Shape:", a1.shape)

print("\n6 x 4:")
print(a2)
print("Shape:", a2.shape)

print("\n2 x 3 x 4:")
print(a3)
print("Shape:", a3.shape)

print("\nBack to 1D:")
print(a1.flatten())

4 x 6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

6 x 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)

2 x 3 x 4:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)

Back to 1D:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [10]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([15, 25, 35, 45, 55])

# One array
one = np.concatenate((a, b))

# Separate rows
rows = np.vstack((a, b))

# Separate columns
columns = np.column_stack((a, b))

print("One-dimensional:")
print(one)
print("Shape:", one.shape)

print("\nRows:")
print(rows)
print("Shape:", rows.shape)

print("\nColumns:")
print(columns)
print("Shape:", columns.shape)

One-dimensional:
[10 20 30 40 50 15 25 35 45 55]
Shape: (10,)

Rows:
[[10 20 30 40 50]
 [15 25 35 45 55]]
Shape: (2, 5)

Columns:
[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
Shape: (5, 2)


In [11]:
import numpy as np

a = np.array([10, 12, 15, 200, 13, 11, 14, 250, 12, 15])

invalid = a[a > 100]

valid = a[a <= 100]

print("Invalid values:")
print(invalid)

print("Valid values:")
print(valid)

print("Mean:")
print(np.mean(valid))

print("Minimum:")
print(np.min(valid))

print("Maximum:")
print(np.max(valid))

Invalid values:
[200 250]
Valid values:
[10 12 15 13 11 14 12 15]
Mean:
12.75
Minimum:
10
Maximum:
15


In [12]:
import numpy as np

image = np.array([
    [0, 0, 0, 255, 255],
    [0, 0, 128, 255, 255],
    [0, 128, 128, 128, 255],
    [0, 0, 128, 0, 0],
    [255, 0, 0, 0, 255]
])

print("Minimum:", np.min(image))

print("Maximum:", np.max(image))

print("Mean:", np.mean(image))

print("Number greater than 100:",
      np.sum(image > 100))

print("Pixels equal to 255:")
print(image[image == 255])

print("Pixels greater than 100:")
print(image[image > 100])

Minimum: 0
Maximum: 255
Mean: 97.0
Number greater than 100: 12
Pixels equal to 255:
[255 255 255 255 255 255 255]
Pixels greater than 100:
[255 255 128 255 255 128 128 128 255 128 255 255]


In [13]:
import numpy as np

A = np.array([12, 15, 14, 18, 20, 17, 16])

B = np.array([10, 13, 15, 16, 19, 21, 18])

print("Mean A:", np.mean(A))
print("Mean B:", np.mean(B))

print("Standard deviation A:", np.std(A))
print("Standard deviation B:", np.std(B))

print("Maximum A:", np.max(A))
print("Maximum B:", np.max(B))

print("Minimum A:", np.min(A))
print("Minimum B:", np.min(B))

print("Difference:")
print(A - B)

if np.std(A) > np.std(B):
    print("A has greater variation")
else:
    print("B has greater variation")

Mean A: 16.0
Mean B: 16.0
Standard deviation A: 2.449489742783178
Standard deviation B: 3.4641016151377544
Maximum A: 20
Maximum B: 21
Minimum A: 12
Minimum B: 10
Difference:
[ 2  2 -1  2  1 -4 -2]
B has greater variation


In [14]:
import numpy as np

def create_data():

    return np.random.randint(1, 101, (10, 5))


def analysis(a):

    print("Data:")
    print(a)

    print("\nShape:", a.shape)
    print("Dimensions:", a.ndim)

    print("\nMean of each variable:")
    print(np.mean(a, axis=0))

    print("\nMean of each experiment:")
    print(np.mean(a, axis=1))

    print("\nMaximum:", np.max(a))
    print("Minimum:", np.min(a))

    average = np.mean(a)

    print("\nOverall mean:", average)

    print("\nValues above mean:")
    print(a[a > average])

    b = a.reshape(5, 10)

    print("\nReshaped array:")
    print(b)

    print("\nFlattened:")
    print(b.flatten())


data = create_data()

analysis(data)

Data:
[[50 30  3  5 46]
 [25 29 37 80 52]
 [76 48 38 55 97]
 [44 96 83 33 13]
 [26  3 80 80 70]
 [17  4 89 61 14]
 [ 7 87 80  4 89]
 [88 84 31 41 55]
 [93 50 61 54 43]
 [55 97 20 73 32]]

Shape: (10, 5)
Dimensions: 2

Mean of each variable:
[48.1 52.8 52.2 48.6 51.1]

Mean of each experiment:
[26.8 44.6 62.8 53.8 51.8 37.  53.4 59.8 60.2 55.4]

Maximum: 97
Minimum: 3

Overall mean: 50.56

Values above mean:
[80 52 76 55 97 96 83 80 80 70 89 61 87 80 89 88 84 55 93 61 54 55 97 73]

Reshaped array:
[[50 30  3  5 46 25 29 37 80 52]
 [76 48 38 55 97 44 96 83 33 13]
 [26  3 80 80 70 17  4 89 61 14]
 [ 7 87 80  4 89 88 84 31 41 55]
 [93 50 61 54 43 55 97 20 73 32]]

Flattened:
[50 30  3  5 46 25 29 37 80 52 76 48 38 55 97 44 96 83 33 13 26  3 80 80
 70 17  4 89 61 14  7 87 80  4 89 88 84 31 41 55 93 50 61 54 43 55 97 20
 73 32]


In [15]:
import numpy as np

# Generate marks
marks = np.random.randint(0, 101, (10, 4))

print("Student Marks:")
print(marks)


# Average of each student
student_average = np.mean(marks, axis=1)

print("\nStudent Averages:")
print(student_average)


# Average of each subject
subject_average = np.mean(marks, axis=0)

print("\nSubject Averages:")
print(subject_average)


# Highest average student
best_student = np.argmax(student_average) + 1

print("\nStudent with highest average:",
      best_student)


# Lowest average student
worst_student = np.argmin(student_average) + 1

print("Student with lowest average:",
      worst_student)


# Highest mark
print("Highest mark:",
      np.max(marks))


# Lowest mark
print("Lowest mark:",
      np.min(marks))


# Students with average above 75
count = np.sum(student_average > 75)

print("Students with average above 75:",
      count)


# Marks greater than 90
print("Marks greater than 90:")
print(marks[marks > 90])


# Grades
def grade(avg):

    if avg >= 90:
        return "A+"
    elif avg >= 80:
        return "A"
    elif avg >= 70:
        return "B"
    elif avg >= 60:
        return "C"
    elif avg >= 50:
        return "D"
    else:
        return "F"


print("\nStudent Grades:")

for i in range(10):

    print(
        "Student", i + 1,
        "Average =", round(student_average[i], 2),
        "Grade =", grade(student_average[i])
    )

Student Marks:
[[ 76  13   6   9]
 [ 77  79  54  10]
 [ 64  50  89  20]
 [  7  49  96   8]
 [ 76  98  12  98]
 [ 38   0  38  66]
 [  4  98  54  29]
 [ 16  63  29  17]
 [ 43  19  11  70]
 [ 15  85 100  29]]

Student Averages:
[26.   55.   55.75 40.   71.   35.5  46.25 31.25 35.75 57.25]

Subject Averages:
[41.6 55.4 48.9 35.6]

Student with highest average: 5
Student with lowest average: 1
Highest mark: 100
Lowest mark: 0
Students with average above 75: 0
Marks greater than 90:
[ 96  98  98  98 100]

Student Grades:
Student 1 Average = 26.0 Grade = F
Student 2 Average = 55.0 Grade = D
Student 3 Average = 55.75 Grade = D
Student 4 Average = 40.0 Grade = F
Student 5 Average = 71.0 Grade = B
Student 6 Average = 35.5 Grade = F
Student 7 Average = 46.25 Grade = F
Student 8 Average = 31.25 Grade = F
Student 9 Average = 35.75 Grade = F
Student 10 Average = 57.25 Grade = D
